/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import model.NhanKhau;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;
import controller.DAO;
import java.text.*;

/**
 *
 * @author Pham Phong
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        comboGioiTinh = new javax.swing.JComboBox<>();
        comboDoTuoi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnThongKe = new javax.swing.JButton();
        btnThongKeTamVang = new javax.swing.JButton();
        btnThongKeTamTru = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);
        
        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("THỐNG KÊ NHÂN KHẨU");

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
                "Họ và tên", "Bí danh", "Ngày tháng năm sinh", "Nơi sinh", "Nguyên quán", "Dân tộc", "Nghề nghiệp", "Nơi làm việc", "Số CMND", "Ngày cấp", "Nơi cấp", "Ngày tháng năm đăng kí thường trú", "Địa chỉ thường trú trước khi chuyển đến"
            }
        ));
        jScrollPane1.setViewportView(tblThongKe);
        if (tblThongKe.getColumnModel().getColumnCount() > 0) {
            tblThongKe.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblThongKe.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblThongKe.getColumnModel().getColumn(2).setPreferredWidth(130);
            tblThongKe.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblThongKe.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblThongKe.getColumnModel().getColumn(5).setPreferredWidth(50);
            tblThongKe.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblThongKe.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblThongKe.getColumnModel().getColumn(8).setPreferredWidth(100);
            tblThongKe.getColumnModel().getColumn(9).setPreferredWidth(100);
            tblThongKe.getColumnModel().getColumn(10).setPreferredWidth(150);
            tblThongKe.getColumnModel().getColumn(11).setPreferredWidth(200);
            
        }

        comboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        comboGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGioiTinhActionPerformed(evt);
            }
        });
        comboGioiTinh.setSelectedItem(null);

        comboDoTuoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dưới 3 tuổi", "3-5 tuổi", "6-10 tuổi", "11-15 tuổi", "16-60 tuổi","Trên 60 tuổi" }));
        comboDoTuoi.setSelectedItem(null);

        jLabel3.setText("Giới tính");

        jLabel4.setText("Độ tuổi");

        jLabel5.setText("Từ năm");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Đến năm");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt){
                btnThongKeActionPerformed(evt);
            }
        });
       

        btnThongKeTamVang.setText("Thống kê tạm vắng");
        btnThongKeTamVang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeTamVangActionPerformed(evt);
            }
        });

        btnThongKeTamTru.setText("Thống kê tạm trú");
        btnThongKeTamTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeTamTruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1900, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThongKeTamTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongKeTamVang, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addGap(794, 794, 794))
            .addGroup(layout.createSequentialGroup()
                .addGap(797, 797, 797)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btnThongKeTamVang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnThongKeTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {
        String tmpAgeValue = (String) comboDoTuoi.getSelectedItem();
        String sexArgumentString = (String) comboGioiTinh.getSelectedItem();
        
        String ageArgumentString;
        
        if(tmpAgeValue==null){
            ageArgumentString = null;
        } else if(tmpAgeValue.equals("Dưới 3 tuổi")){
            ageArgumentString = "< 3";
        } else if(tmpAgeValue.equals("3-5 tuổi")){
            ageArgumentString = "BETWEEN 3 AND 5";
        } else if(tmpAgeValue.equals("6-10 tuổi")){
            ageArgumentString = "BETWEEN 6 AND 10";
        } else if(tmpAgeValue.equals("11-15 tuổi")){
            ageArgumentString = "BETWEEN 11 AND 15";
        } else if(tmpAgeValue.equals("16-60 tuổi")){
            ageArgumentString = "BETWEEN 16 AND 60";
        } else{
            ageArgumentString = "> 60";
        }
        ArrayList<NhanKhau> list = (new DAO().getNhanKhauListByCriteria(ageArgumentString, sexArgumentString));
        
        //không chuyển Date thành String trước khi addRow
        //có thể uncomment đoạn code dưới
        DefaultTableModel model = (DefaultTableModel) tblThongKe.getModel();
        for (NhanKhau nk : list){
            model.addRow(new Object[]{nk.getTen(),
                                      nk.getBietDanh(),
                                      nk.getNgaySinh(),
                                      nk.getNoiSinh(),
                                      nk.getQueQuan(),
                                      nk.getDanToc(),
                                      nk.getNgheNghiep(),
                                      nk.getNoiLamViec(),
                                      nk.getSoCMND(),
                                      nk.getNgayCap(),
                                      nk.getNoiCap(),
                                      nk.getNgayDangKiThuongTru(),
                                      nk.getDiaChiTruocKhiChuyenDen()
            });
        }
        
        //có chuyển Date thành String trước khi addRow
//        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
//        DefaultTableModel model = (DefaultTableModel) tblThongKe.getModel();
//        for (NhanKhau nk : list){
//            String strNgaySinh = dateFormat.format(nk.getNgaySinh());
//            String strNgayCap = dateFormat.format(nk.getNgayCap());
//            String strNgayDangKiThuongTru = dateFormat.format(nk.getNgayDangKiThuongTru());
//            model.addRow(new Object[]{nk.getTen(),
//                                      nk.getBietDanh(),
//                                      strNgaySinh,
//                                      nk.getNoiSinh(),
//                                      nk.getQueQuan(),
//                                      nk.getDanToc(),
//                                      nk.getNgheNghiep(),
//                                      nk.getNoiLamViec(),
//                                      nk.getSoCMND(),
//                                      strNgayCap,
//                                      nk.getNoiCap(),
//                                      strNgayDangKiThuongTru,
//                                      nk.getDiaChiTruocKhiChuyenDen()
//            });
//        }
    }
        
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnThongKeTamVangActionPerformed(java.awt.event.ActionEvent evt) {    
                String tmpAgeValue = (String) comboDoTuoi.getSelectedItem();
        String sexArgumentString = (String) comboGioiTinh.getSelectedItem();
        
        String ageArgumentString;
        
        if(tmpAgeValue.equals("null")){
            ageArgumentString = "null";}
//        } else if(tmpAgeValue.equals("Dưới 3 tuổi")){
//            ageArgumentString = "< 3";
//        } else if(tmpAgeValue.equals("3-5 tuổi")){
//            ageArgumentString = "BETWEEN 3 AND 5";
//        } else if(tmpAgeValue.equals("6-10 tuổi")){
//            ageArgumentString = "BETWEEN 6 AND 10";
//        } else if(tmpAgeValue.equals("11-15 tuổi")){
//            ageArgumentString = "BETWWEN 11 AND 15";
//        } else if(tmpAgeValue.equals("16-60 tuổi")){
//            ageArgumentString = "BETWEEN 16 AND 60";
//        } else{
//            ageArgumentString = "> 60";
//        }
    }                                        

    private void btnThongKeTamTruActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void comboGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThongKeTamVang;
    private javax.swing.JButton btnThongKeTamTru;
    private javax.swing.JComboBox<String> comboGioiTinh;
    private javax.swing.JComboBox<String> comboDoTuoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThongKe;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration                   
}